settings_factory:
  code: 77
  01_timeout_minutes: 5
  02_start_min: 5
  03_cadence_clean: 45
  04_light_time: 1
    default: 1
  05_start_time: 0.3
    default: 1
    comment: flamme light
  06_auger_p1: 0.7
    default: 1.2
  07_auger_p5: 1.8
    default: 1.8
  08_cleaning_speed: 2700
    real: 2800
  09_auger_cleaning: 0.5
  10_threshold_off: 60
  11_alarm_delay: 30
  12_cleaning_duration: 30
  13_min_threshold: 45
  14_max_threshold: 200
  15_blower: 65
  16_smokey_on: 2000
  17_smokey_start: 2000
  18_smokey_p1: 1410
    real: 1740
  19_smokey_p5: 1900
  20_blower_p1: 180
  21_blower_p5: 210
  22_encoder: on
  23_blower_clean: 130
settings_type_pellet: 0
settings_type_chimney: 9


















